[package]
name = "alans_site_builder"
version = "0.1.0"
edition = "2021"

[dependencies]
minijinja = { version = "2.6.0", features = ["custom_syntax", "loader"] }
regex = "1.10.4"
syntect = "5.2.0"
walkdir = "2"
